{sy}hisat2
OxfordCMS/OCMS_Shotgun pull request #52
Opened 2024-11-13 16:43 UTC by schyen

Adding hisat as a tool to align and filter host reads. Made several changes to base class `matchReference` and added a new base class. Also added remove_host as a separate stand-alone pipeline.

2025-01-20 14:24 UTC, nickilott requested changes
Hello!

I think there are some dependency issues in here still - the pipeline doesn't run all the way through for me and the first error was not finding that dehost files were there to be counted in the summaries

<img width="725" alt="image" src="https://github.com/user-attachments/assets/4ff655f0-f9c5-44c5-b4b3-105c5e4901e3" />

I think this is because of the upstream dependencies:

```removeHost``` follows just the hisat summaries and not sure if that task is even needed. Everything downstream of the host removal should be dependent on ```alignAndRemoveHost``` as far as I can see as this determines the input fastq files. However, if I change for example ```maskLowComplexity``` to depend on ```alignAndRemoveHost``` I get an error that files can't be opened because they are NoneType:

<img width="547" alt="image" src="https://github.com/user-attachments/assets/4cebefab-0429-40d5-abf0-dd5ae8dfb3b2" />

Is that because of empty fastq3's from hisat?

2025-01-20 14:24 UTC, nickilott commented on ocmsshotgun/pipeline_preprocess.py
> +@follows(mergeHisatSummary, cleanHisat)
I'm not sure that this is what you need here...if I'm reading correctly this is taking the summaries where you want the output reads? It also isn't taking anything from bmtagger if that is run instead. So the things downstream don't run for me? like maskLowComplexity I think and the counting for the summaries

2025-01-23 09:20 UTC, schyen commented on ocmsshotgun/pipeline_preprocess.py
> +@follows(mergeHisatSummary, cleanHisat)
I've added alignAndRemoveHost to this now

2025-01-26 09:15 UTC, nickilott requested changes
I have tested pipeline_preprocess with both hisat2 and bmtagger and both produce the expected results based on the processing summary file. There was just one additional bug here with the bmtagger statement build that I have highlighted.

2025-01-26 09:15 UTC, nickilott commented on ocmsshotgun/pipeline_preprocess.py
> +        tool = pp.bmtagger(fastq1, outfile, **PARAMS)
this needs to be changed to ```tool = pp.bmtagger(infile, outfile, **PARAMS)```

2025-01-27 09:47 UTC, schyen commented on ocmsshotgun/pipeline_preprocess.py
> +        tool = pp.bmtagger(fastq1, outfile, **PARAMS)
Ah good catch! I've fixed it now

2025-01-27 10:28 UTC, nickilott approved these changes

2025-01-27 10:34 UTC, merged